apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-frontend
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/toannd135/typ-frontend.git'
      targetRevision: HEAD
      ref: values
    # - repoURL: 'https://github.com/toannd135/typ-frontend.git'
    #   targetRevision: HEAD
      path: 'helm-chart'
      # helm:
      #   valueFiles:
      #   - $values/helm-values/values-prod.yml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: typ-app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
