apiVersion: v1
kind: Service
metadata: 
  name: {{ include "backend-chart.fullname" . }}
  labels: {{ include "backend-chart.labels" . | nindent 4 }}
spec:
  selector: {{ include "backend-chart.selectorLabels" . | nindent 4}}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}